name: dataj-installs

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - jupyter
  - jupyterlab
  - notebook
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - plotly
  - openpyxl
  - pip
